### ISSUE TITLE
Logged in user gets "Not Authorized" screen during editing session

### ISSUE THREAD

**Issue by jcahail** [azavea/opendataphilly-ckan#61]
![image](https://cloud.githubusercontent.com/assets/24727081/24358860/87395708-12d0-11e7-94f8-43b640d921d9.png)

Kistine and Tim are seeing the screen above when either one of them tries to edit related items on https://www.opendataphilly.org/dataset/opa-property-assessments/related or https://www.opendataphilly.org/dataset/citybudget/related; the issue is NOT present when editing https://www.opendataphilly.org/dataset/community-health-assessment/related.

**Comment by KlaasH** [comment]
Observations:
- Only superusers and the user who created a related item can edit or delete it
- The Edit button shows up on all related items for everyone, even if you're not logged in. There's logic in the template to show it only to those allowed to change it, but it's not working right.  Haven't figured out why yet.
- I'm >90% sure that nothing changed with the deploy with regard to who's allowed to edit related items.  I thought it might be fallout from the highlight-related plugin, but removing that doesn't fix it.  I think what changed was that related items are now front and center, so the existing bug is much more noticeable.  (So in a way it is fallout from the new extension...)
- If Tim is Tim Wisniewski, he owns only one related item, "City Employee Salaries Visualization", on "Employee Salaries & Overtime"
- Kistine's account with username "kistine" owns no related items, but "kistine-carolan-9469" owns
   - "City’s New Digital Resource on Public Health (Blogpost)" (on Community Health Assessment)
   - "Map of Street Trees" (on Philadelphia Street Tree Inventory)
   - "FY16Q2 City Employee Salaries Visualization" (on Employee Salaries & Overtime)
   - "Community Health Assessment Reports" (on Community Health Assessment)
- On the other datasets above:
   - The City Operating Budget related items are owned by Stacy Mosely except for "Open Budget Explorer" which is owned by John Branigan.
   - The OPA related items are all owned by Jim MacMillan.

I don't think we can change the permissions logic.  We could probably figure out a way to change ownership of related items, though I don't see a way to do it in the front-end.  It also might be that the implementation is different in the new version of the related plugin (see https://github.com/azavea/ckanext-odp_theme/issues/52).

We should, however, figure out how to stop showing the Edit button to people who aren't allowed to edit.  I just made issue #63 for that.

**Comment by KlaasH** [comment]
Further investigation has mostly reinforced the above.

The permission check for changing related items is [here](https://github.com/ckan/ckan/blob/ckan-2.2.4/ckan/logic/auth/update.py#L142) and only allows the creator/owner to make changes.  Compare to [the logic for resources](https://github.com/ckan/ckan/blob/ckan-2.2.4/ckan/logic/auth/update.py#L72) which does a check for whether the user has permissions on the connected dataset.  Actually it turns out Related objects are many-to-many, though I don't see a way to add an existing one to a second datasource, and indeed all the ones in the database are one-to-one.  I also haven't seen a way to change or even see who owns a Related item.

We could change the permission logic--replacing the user check with
```
    if not userobj or (userobj.id != related.owner_id and not
                       new_authz.is_authorized('package_update',
                                               context,
                                               {'id': related.datasets[0].id}).get('success')):
        return {'success': False, 'msg': _('Not authorized to edit related item')}
```
would do the trick, I think, but we haven't dug in and overridden the core CKAN logic elsewhere and I'm not sure this is the place to start, especially since the whole feature was refactored and moved into an extension in 2.5.

The immediate steps to address the city's problems with not being able to change their related items would be, I think:
- Have Kistine go back to using her old account (`kistine-carolan-9469`), since that owns some of the related items.
- When they find one that's uneditable, make have the person most likely to be maintaining it in the future create a new copy, then get a superuser to delete the old one.  Or we could change ownership directly in the database, but that seems like a less convenient and more complicated process.
